version: '1'

services:

  db:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - "postgres-data-simplebank:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: simplebank
      POSTGRES_PASSWORD: 1234abcd
      POSTGRES_DB: simplebank

volumes:
  postgres-data-simplebank:
    driver: local
